Filas/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Filas.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Filas/Pages/Index.cshtml.cs
using Filas.DTOs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Filas.Pages
{
    public class IndexModel : PageModel
    {
        /*Abre o model da Index com o database e a lista de reserva "preenchidas"*/
        public IndexModel()
        {
            FilasDb = new FilasDbContext();
            ReservaList = new List<Reserva>();
        }
        public FilasDbContext FilasDb { get; set; }
        public List<Reserva> ReservaList { get; set; } //variavel publica, q da pra inserir (set) e consultar (get)

        public PageResult OnGet()
        {
            ReservaList = FilasDb.Reservas.Where(x => x.ENTROU == false).ToList();
            ViewData["ListItemsMesa"] = new SelectList(ListItemsMesa(), "Value", "Text");

            return Page();
        }

        public ActionResult OnPost(Reserva reserva)
        {
            var dsMesa = getMesa(reserva.QTD_PESSOAS);
            var mesaReserva = FilasDb.Mesas.FirstOrDefault(x => x.DS_MESA == dsMesa);

            if (mesaReserva == null)
            {
                var novaMesa = new Mesa();
                novaMesa.DS_MESA = dsMesa;

                FilasDb.Add(novaMesa);
                FilasDb.SaveChanges();

                mesaReserva = novaMesa;
            }

            reserva.ID_MESA = mesaReserva.ID_MESA;

            //Adiciona na instância Reservas do banco de dados o que vem do parâmetro do OnPost (reserva)
            FilasDb.Reservas.Add(reserva);
            //Salva as mudanças
            FilasDb.SaveChanges();
            //Retorna a Index com as mudanças feitas
            return RedirectToPage("Index");
        }

        public string getMesa(int QTD_PESSOAS)
        {
            switch (QTD_PESSOAS)
            {
                case 1: return "Um";
                case 2: return "Dois";
                case 3: return "Três";
                case 4: return "Quatro";
                case 5: return "Cinco";
                case 6: return "Seis";
                case 7: return "Sete";
                case 8: return "Oito";
                case 9: return "Nove";
                case 10: return "Dez";

                default: return "10+";
            }
        }

        public ActionResult OnPostEntrar(int ID_RESERVA)
        {
            var reserva = FilasDb.Reservas.Find(ID_RESERVA);
            if (reserva != null)
            {
                reserva.ENTROU = true;
                FilasDb.SaveChanges();
            }
            return RedirectToPage("Index");
        }

        public IEnumerable<SelectListItem> ListItemsMesa()
        {
            var mesas = FilasDb.Mesas.ToList();

            IList<SelectListItem> items = new List<SelectListItem>();
            
            foreach (var item in mesas)
            {
                items.Add(new SelectListItem { Value = item.ID_MESA.ToString(), Text = item.DS_MESA });
            }
            return items;
        }

    }

}

Filas/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Filas.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Filas/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Início";
    var contadorPosicao = 1;
    var comparadorQtdPessoas = 0;
}

<div class="text-center">
    <h2>Total de mesas em espera para</h2>
    <div class="container-painel">
        @foreach (var i in Model.ReservaList.Where(e => e.ENTROU == false).OrderBy(y => y.QTD_PESSOAS).GroupBy(x => x.ID_MESA))
        {
            <div class="itens-painel">
                <text class="numero-pessoas">
                    @foreach (var item in ViewBag.ListItemsMesa)
                    {
                        if (item.Value == i.Key.ToString())
                            @item.Text
                    }
                </text> <br />
                <text class="numero-mesas">@i.Count()</text>
            </div>
        }
    </div>

    <form method="post">
        <div class="form-group container-formulario">
            <div style="width: 350px">
                <input name="NOME_RESERVA" class="form-control" type="text" value="" placeholder="Nome e sobrenome da reserva" />
            </div>
            <div style="width: 180px">
                <input name="QTD_PESSOAS" class="form-control" type="text" value="" placeholder="Para quantas pessoas?" />
            </div>
            <div>
                <button class="btn btn-outline-success" type="submit"><b>Adicionar à fila</b></button>
            </div>
        </div>
    </form>

    <div class="input-group campo-pesquisa mb-3">
        <div style="width: 270px">
            <input name="filtro" id="campoPesquisa" class="form-control" type="text" placeholder="Buscar" />
        </div>
        <div class="input-group-append" style="z-index: -1">
            <span class="input-group-text">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="24" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                    <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                </svg>
            </span>
        </div>
    </div>

    <div class="container-tabela">
        <div style="width: 678px">
            <table class="table table-bordered">
                <thead class="bg-black" style="color: white">
                    <tr>
                        <th style="min-width: 85px">Posição</th>
                        <th style="width: 100%" class="col-nome">Nome</th>
                        <th style="min-width: 100px">Mesa para</th>
                        <th style="min-width: 85px">Horário</th>
                        <th style="min-width: 150px">Concluir/Cancelar</th>
                    </tr>
                </thead>
                <tbody id="myTable">
                    @foreach (var i in Model.ReservaList.OrderBy(x => x.QTD_PESSOAS).ThenBy(y => y.HORA_RESERVA))
                    {
                        @if (comparadorQtdPessoas != i.QTD_PESSOAS)
                        {
                            contadorPosicao = 1;
                            comparadorQtdPessoas = i.QTD_PESSOAS;
                        }
                        <tr>
                            <td>
                                @(contadorPosicao + "º")
                            </td>
                            <td class="col-nome filtro">
                                @i.NOME_RESERVA
                            </td>
                            <td class="filtro">
                                @i.QTD_PESSOAS
                            </td>
                            <td>
                                @i.HORA_RESERVA.ToString("HH:mm:ss")
                            </td>
                            <td>
                                <form method="post">
                                    <button name="ID_RESERVA" asp-page-handler="Entrar" value="@i.ID_RESERVA" type="submit" class="botao-concluir">
                                        <img src="lib/bootstrap/dist/icons/check-circle.svg" class="img-concluir">
                                    </button>
                                </form>
                            </td>
                        </tr>
                        contadorPosicao++;
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $("#campoPesquisa").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function() {
                var length = this.children.length;
                for (let i = 0; i < length; i++) {
                    var TD = this.children[i];

                    if (TD.classList.contains("filtro")) {
                        $(this).toggle($(TD).text().toLowerCase().indexOf(value) > -1);

                        if ($(TD).text().toLowerCase().indexOf(value) > -1)
                            return;
                    }
                }
            });
        });
    });
</script>

@*<script>
    $(document).ready(function() {
        $("#campoPesquisa").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            var habilitaTr = false;
            $("#myTable tr").filter(function() {
                var lenght = this.children.length;
                for (let i = 0; i < lenght; i++) {
                    var TD = this.children[i];

                    if (TD.classList.contains("filtro"))
                        habilitaTr = $(TD).text().toLowerCase().indexOf(value) > -1;
                    else
                        habilitaTr = false;

                    $(this).toggle(habilitaTr);

                    if (habilitaTr)
                        return;
                }
            });
        });
    });
</script>*@

Filas/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Filas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Filas.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Filas.styles.css" asp-append-version="true" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index" style="font-size: 25px; font-weight: bold">F I L A S</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @*<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                </li>
                <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                </li>
                </ul>
                </div>*@
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Filas - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>